# Jaeger Docker Compose
# construction-platform/monitoring/jaeger.yml

version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"  # Agent (zipkin.thrift)
      - "6831:6831/udp"  # Agent (jaeger.thrift)
      - "6832:6832/udp"  # Agent (jaeger.thrift)
      - "5778:5778"      # Agent config
      - "16686:16686"    # UI
      - "14268:14268"    # Collector HTTP
      - "14250:14250"    # Collector gRPC
      - "9411:9411"      # Zipkin
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
